theme = "catppuccin_frappe"

[editor]
true-color = true
bufferline = "always"

[editor.statusline]
left = ["mode", "file-name"]
center = ["spinner", "position", "position-percentage"]
right = ["diagnostics", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"